---
title: "Kickers"
output: html_document
---

<style type="text/css">

body {
  font-size: 14pt;
}

h1 { /* Header 1 */
  font-size: 34px;
  color: darkmagenta;
  font-weight: bold;
}
</style>

[FantasyPros Draft Pick](https://www.fantasypros.com/nfl/rankings/k-cheatsheets.php){target="_blank"}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include=TRUE, warning=FALSE, message = FALSE)
```

```{r}
library(here)
library(tidyverse) 
library(janitor)
library(httr)
library(jsonlite)
library(RCurl)
library(glue)
library(mysportsfeedsR)
library(kableExtra)
library(gt)
library(shiny)
library(reactable)
library(ggrepel)
library(ggeasy)

setwd(here("../"))
source("login_creds.R")
```

<!-- # API request -->
```{r, inclue=FALSE}
res = GET('https://api.mysportsfeeds.com/v2.0/pull/nfl/2020-2021-regular/player_stats_totals.json', 
          add_headers(Authorization = paste("Basic", auth)))
api_response <- content(res, as="text")
api_response <- jsonlite::fromJSON(api_response, flatten=TRUE)

player_stats <- api_response$playerStatsTotals %>%
  as_tibble() %>%
  clean_names()  %>%
  select(first_name = player_first_name, last_name = player_last_name, position = player_primary_position, team = team_abbreviation, games_played = stats_games_played, fg_made = stats_field_goals_fg_made, fg_att = stats_field_goals_fg_att, fg_pct = stats_field_goals_fg_pct, fg1_19pct = stats_field_goals_fg1_19pct, fg1_19made = stats_field_goals_fg_made1_19, fg1_19att = stats_field_goals_fg_att1_19, fg20_29pct = stats_field_goals_fg20_29pct, fg20_29made = stats_field_goals_fg_made20_29, fg20_29att = stats_field_goals_fg_att20_29, fg30_39pct = stats_field_goals_fg30_39pct, fg30_39made = stats_field_goals_fg_made30_39, fg30_39att = stats_field_goals_fg_att30_39, fg40_49pct = stats_field_goals_fg40_49pct, fg40_49made = stats_field_goals_fg_made40_49, fg40_49att = stats_field_goals_fg_att40_49, fg_50pct = stats_field_goals_fg50plus_pct, fg_50made = stats_field_goals_fg_made50plus, fg_50att = stats_field_goals_fg_att50plus)
```

- Indexed games so everyone is scored based on playing all 16 games
- `Golden Ratio`: a composite score including:
   - FG percent (not indexed) 20% weight 
   - FG attempts 20% weight 
   - FG Made 0-39 x3 20% weight 
   - FG Made 40-49 x4 20% weight 
   - FG Made 50+ x5 20% weight 
- Top 25
```{r}
k_stats <- player_stats %>%
  select(first_name, last_name, position, team, games_played, fg_made, fg_att, fg_pct, fg1_19made, fg1_19att, fg1_19pct, fg20_29made, fg20_29att, fg20_29pct, fg30_39made, fg30_39att, fg30_39pct, fg40_49made, fg40_49att, fg40_49pct, fg_50made, fg_50att, fg_50pct) %>%
  filter(position == "K" & last_name != "Long" & games_played > 10) %>% 
  select(first_name, last_name, team, games_played, fg_att, fg_pct, fg1_19made, fg20_29made, fg30_39made, fg40_49made, fg_50made, fg_pct) %>%
  mutate(games_index = games_played/16) %>%
  relocate(games_index, .before = fg1_19made) %>%
  mutate(full_name = paste(first_name, last_name),
         fg_att = fg_att/games_index,
         fg1_19made = fg1_19made/games_index,
         fg20_29made =fg20_29made/games_index,
         fg30_39made = fg30_39made/games_index,
         fg40_49made = fg40_49made/games_index,
         fg_50made = fg_50made/games_index,
         fg1_39made = fg1_19made + fg20_29made + fg30_39made,
         fg1_39made_pts = (fg1_19made + fg20_29made + fg30_39made)*3,
         fg40_49made_pts = fg40_49made*4,
         fg_50made_pts = fg_50made*5, 
         fg1_39made_pts_i = fg1_39made_pts/max(fg1_39made_pts),
         fg40_49made_pts_i = fg40_49made_pts/max(fg40_49made_pts),
         fg_50made_pts_i = fg_50made_pts/max(fg_50made_pts),
         golden_ratio = (fg_pct*1.2)+(fg_att*1.2)+(fg1_39made_pts_i*1.2)+(fg40_49made_pts_i*1.2)+(fg_50made_pts_i*1.2)) %>%
  arrange(desc(golden_ratio)) %>%
  #select(full_name, team, games_played, pass_yards, pass_td, rush_yards, rush_td, sacks, golden_ratio) %>%
  mutate(rank = 1:length(golden_ratio)) %>%
  relocate(rank) %>%
  filter(rank < 25) %>%
  mutate_if(is.numeric, round, 2)

k_stats_picks <- k_stats %>%
  select(rank, full_name, team, games_played, fg_att, fg_pct, fg1_39made, fg40_49made, fg_50made, golden_ratio) %>%
  #select(rank, full_name, team, games_played, fg_att, fg1_39pct, fg_40plus_pct, golden_ratio) %>%
  rename(Rank = rank, 
         "Name" = full_name,
         Team = team,
         "Games Played" = games_played,
         "FG Attempts" = fg_att,
         "FG %" = fg_pct,
         "FG Made 1-39" = fg1_39made,
         "FG Made 40-49" = fg40_49made,
         "FG Made 50+" = fg_50made,
         "Golden Ratio" = golden_ratio)

reactable(k_stats_picks, selection = "multiple", defaultPageSize = 24, highlight=TRUE, striped=TRUE, width=1100)

```

# Field Goals
```{r}
k_stats_plot <- k_stats %>%
  filter(rank < 30)

ggplot(k_stats_plot, aes(fg_pct, fg_att, label = last_name)) +
  geom_point() +
  geom_text_repel() +
  theme_bw() +
  labs(x="FG %", y="FG Attempts") +
  easy_text_size(15)
```


```{r, include=FALSE}
# - fg_att overall .3
# - fg < 40 percent .35
# - fg > 40 made .35
# k_stats <- player_stats %>%
#   select(first_name, last_name, position, team, games_played, fg_made, fg_att, fg_pct, fg1_19made, fg1_19att, fg1_19pct, fg20_29made, fg20_29att, fg20_29pct, fg30_39made, fg30_39att, fg30_39pct, fg40_49made, fg40_49att, fg40_49pct, fg_50made, fg_50att, fg_50pct) %>%
#   filter(position == "K" & games_played > 10 & last_name != "Long") %>% #& games_played > n_min_games_played
#   select(-position) %>%
#   #mutate_all(~replace(., is.nan(.), 0)) %>%
#   mutate(fg1_39made = fg1_19made + fg20_29made + fg30_39made,
#          fg1_39att = fg1_19att + fg20_29att + fg30_39att,
#          fg1_39pct = fg1_39made/fg1_39att, 
#          fg_40plus_made = fg40_49made + fg_50made) %>%
#          #fg_40plus_att = fg40_49att + fg_50att,
#          #fg_40plus_pct = fg_40plus_made/fg_40plus_att) %>%
#   select(first_name, last_name, team, games_played, fg_made, fg_att, fg_pct, fg1_39made, fg1_39att, fg1_39pct, fg_40plus_made) %>% # fg_40plus_att, fg_40plus_pct
#   mutate(games_index = games_played/16) %>%
#   relocate(games_index, .before = fg_made) %>%
#   mutate(full_name = paste(first_name, last_name),
#          fg_made = fg_made/games_index,
#          fg_att = fg_att/games_index, # across(pass_yards:sacks, ~ .x/games_index) this works but over writes variable name so no good
#          fg_pct = fg_pct/games_index,
#          fg_made_i= fg_made/max(fg_made),
#          fg_att_i= fg_att/max(fg_att),
#          fg_pct_i= fg_pct/max(fg_pct),
#          #golden_ratio = (fg_made_i*1.4)+(fg_att_i*1.20)+(fg_pct_i*1.4)) %>%
#          fg1_39pct = fg1_39pct/games_index,
#          fg_40plus_made = fg_40plus_made/games_index,
#          #fg_40plus_pct = fg_40plus_pct/games_index,
#          fg1_39pct_i = fg1_39pct/max(fg1_39pct),
#          fg_40plus_made_i = fg_40plus_made/max(fg_40plus_made),
#          #fg_40plus_pct_i = fg_40plus_pct/max(fg_40plus_pct),
#          golden_ratio = (fg_att_i*1.3)+(fg_made_i*1.35)+(fg_40plus_made*1.35)) %>%
#   arrange(desc(golden_ratio)) %>%
#   #select(full_name, team, games_played, pass_yards, pass_td, rush_yards, rush_td, sacks, golden_ratio) %>%
#   mutate(rank = 1:length(golden_ratio)) %>%
#   relocate(rank) %>%
#   filter(rank < 25) %>%
#   mutate_if(is.numeric, round, 2)
# 
# k_stats_picks <- k_stats %>%
#   select(rank, full_name, team, games_played, fg_made, fg_att, fg_pct, golden_ratio) %>%
#   #select(rank, full_name, team, games_played, fg_att, fg1_39pct, fg_40plus_pct, golden_ratio) %>%
#   rename(Rank = rank, 
#          "Name" = full_name,
#          Team = team,
#          "Games Played" = games_played,
#          "FG Made" = fg_made,
#          "FG Attempts" = fg_att, 
#          "FG %" = fg_pct,
#          #"FG < 40" = fg1_39pct,
#          #"FG > 40" = fg_40plus_pct, 
#          "Golden Ratio" = golden_ratio)
# 
# #write.csv(rb_stats, "rb_picks.csv")
# 
# reactable(k_stats_picks, selection = "multiple", defaultPageSize = 24, highlight=TRUE, striped=TRUE, width=1000)

```
